### ISSUE TITLE
Impossible to create a "Custom Configuration"

### ISSUE THREAD

**Issue by rubru70** [imunes/imunes#100]
I work in VirtualBox Imunes. I get an error creating a customer configuration in a widget/pc.
I copied the log and made a screendump.

Any idea how to workaround this?
I am investigating the possibilities to use imunes as tool for our students at Hogeschool Leiden (The Netherlands).
![Screenshot_2020-02-05_13-51-06](https://user-images.githubusercontent.com/28634468/73843628-478f9680-481f-11ea-9c3a-d1bb6d4123f2.png)

bad window path name ".cfgEditor.nb.test"
bad window path name ".cfgEditor.nb.test"
    while executing
"ttk::frame $wi.nb.$cfgID "
    (procedure "createTab" line 7)
    invoked from within
"createTab $node $cfgName"
    (procedure "createNewConfiguration" line 14)
    invoked from within
"createNewConfiguration .cfgEditor n0"
    invoked from within
".cfgEditor.options.b invoke "
    invoked from within
".cfgEditor.options.b instate !disabled { .cfgEditor.options.b invoke } "
    invoked from within
".cfgEditor.options.b instate pressed { .cfgEditor.options.b state !pressed; .cfgEditor.options.b instate !disabled { .cfgEditor.options.b invoke } } "
    (command bound to event)

**Comment by denisSal** [comment]
Hi!

This happens because the name input box has a "wrong" text format - it should just be 'test' (without .conf). We don't sanitize the input, but the `.` character seems to be causing problems here.

This new configuration name is just a name for the drop down menu on a previous dialog box, it does not create a file on your filesystem with this name (see [this](http://imunes.net/dl/guide/node5.html#SECTION00521000000000000000)).

When the node runs, IMUNES then copies the content of this entry to the node as `/custom.conf` and executes it.

**Comment by rubru70** [comment]
> Hi!
> 
> This happens because the name input box has a "wrong" text format - it should just be 'test' (without .conf). We don't sanitize the input, but the `.` character seems to be causing problems here.
> 
> This new configuration name is just a name for the drop down menu on a previous dialog box, it does not create a file on your filesystem with this name (see [this](http://imunes.net/dl/guide/node5.html#SECTION00521000000000000000)).
> 
> When the node runs, IMUNES then copies the content of this entry to the node as `/custom.conf` and executes it.

Thanks Denis for the quick explanation!
