### ISSUE TITLE
Link bandwidth has unexpected impact on latency

### ISSUE THREAD

**Issue by vgiotsas** [imunes/imunes#102]
I have a very simple topology like the following:

![image](https://user-images.githubusercontent.com/5067019/78196791-5d19e900-747b-11ea-9d55-8a4fed030c9d.png)

All the router and link configurations are the default.
When I ping router2 from router1 leaving the default link bandwidth and delay, I get an average RTT of 0.09, which is expected. 

When I change just the link bandwidth to 100Mbps without changing the link delay, I'd expect that the RTT won't be affected. However, the average RTT increases to 20ms which seems wrong. Does changing the bandwidth correlate with other link properties, or is it a bug?

My IMUNES version is v2.3.0 (git 447d09a)

**Comment by denisSal** [comment]
Hello, thank you for your feedback!

I assume you are running this on FreeBSD, so I tried your setup on my VM. Indeed, this seems wrong.

If I set the bandwidth to 976000001 bps, the ping RTT is under 1ms, but if I decrease it to 976000000 bps, it goes back to around 20ms. But (for 976000000), running `ping -i 0.00001 -c 20 10.0.0.2` shows it's actually around 1ms for every packet except the last one...

I'll research this, but I think this has something to do with `ng_pipe` netgraph module and maybe how it simulates some delays in queues depending on the bandwidth...

**Comment by denisSal** [comment]
You can play with the value of `kern.hz` to lower the RTT if you run IMUNES in the VM.

Just change it to some value (e.g. 10000) in `/boot/loader.conf` and reboot:
```kern.hz=10000```

**Comment by vgiotsas** [comment]
Thanks a lot @denisSal for looking into it.

This change makes the RTT increase smaller, but I think it's still visible, and because I want to use it for a university course I'm still concerned the RTT increase may confuse students.

**Comment by gornjas** [comment]
Hi @vgiotsas,

the delay you observe with non-zero bandwidth is both intentional and correct, as we are trying to emulate properties of a physical link, not just rate-limit flows. The observed delay is usually referred to as transmission or serialization delay, as opposed to the propagation delay, which is another constant which may be configured separately. The serialization delay is a function of both bit rate and each packet size, and the resulting delay is computed around line 790 in sys/netgraph/ng_pipe.c which you can find in FreeBSD kernel source tree (also around line 110 if the outbound queue is configured for WFQ). As @denisSal explained above, the timeslice resolution depends on kern.hz setting, the faster the clock ticks, the more precise emulated delays should be observable.
