### ISSUE TITLE
Connecting virtual network to the internet

### ISSUE THREAD

**Issue by soso288** [imunes/imunes#109]
I tried the above mentioned by following the steps in the imunes manual and on github wiki but it doesn't seem to work.
Here is what I did exactly: 
1. created an external interface node, picked an interface (docker0) and linked it to a router which is connected to pc1 which I want to have an internet connection on
2. changed the MAC-address of the router so it's the same as the interface's MAC-address and gave it an IP from the interface's subnet (IP Interface: 172.17.0.1, IP router: 172.17.0.4)
3. created a static route on the router: 0.0.0.0/0 172.17.0.1
I wasn't sure if that step was necessary but I tried it anyways:
4. created an ip route 10.0.1.0/24 via 172.17.0.4 on the host machine (the IP-addr of pc1 is 10.0.1.20)
I'm neither able to ping pc1 from the host machine nor the other way around and pc1 also has no internet connection.
What am I doing wrong? I'm thankful for anyone who can help :)

**Comment by denisSal** [comment]
Hello, sorry for the late reply!

There is an option in every L3 node "Attach external docker interface". If you turn it on in the router configuration dialog, you will be able to get internet access by setting the default route to 172.17.0.1

I then recommend setting up NAT on the router so that pc1 can use private IP addresses.

Cheers,
Denis
