### ISSUE TITLE
bhyve support

### ISSUE THREAD

**Issue by Dautor** [imunes/imunes#118]
It would be nice to have support for VMs.
This would allow simulation of different operating systems and their interactions.

[bhyve](https://docs.freebsd.org/en/books/handbook/virtualization/#virtualization-host-bhyve) is a hypervisor that is preinstalled on x86_64 FreeBSD systems.
It is fairly simple to use and should be relatively easy to add support for.

Device passthrough could also be useful here, allowing guest VMs to have PFs and VFs of their own.

**Comment by denisSal** [comment]
Hi Dautor,

As announced, I'm continuing the discussion initiated in #117... To begin with, there's already a similar request (see #98), but since there's renewed demand for this feature, I'll elaborate a bit and share my thoughts on it.

However appealing it may sound, I don't want to transform IMUNES into a hypervisor for all possible types of virtualization. It's a significant undertaking that would imply (over) substantial changes and continuous maintenance of multiple virtualization systems on various platforms.

On the other hand, it would be beneficial if virtual machines could somehow be integrated into IMUNES topologies without IMUNES needing to account for and be aware of all parameters during the machine's startup/configuration/shutdown. What I propose, and what would be entirely feasible, is to create a node (External node/host/machine?) that serves to define the parameters with which the IMUNES network would connect to that node. According to [this](https://klarasystems.com/articles/using-netgraph-for-freebsds-bhyve-networking/) article, it's possible to use netgraph (which IMUNES uses on FreeBSD) to connect a bhyve virtual machine to the host network. This means, for example, that in that node, only netgraph node and its hook could be defined, and IMUNES would connect it to nodes within the running topology.

Later, this node could be expanded with additional options (e.g., startup/terminate commands, a command to open the shell, etc.). The user would have complete responsibility for defining all aspects of these commands - IMUNES would only need to run them and not worry about any errors or misconfigurations.

If you find this idea appealing, I can try experimenting with it. Feel free to share your advice and opinions.

Best regards,
Denis

**Comment by Dautor** [comment]
That sounds like a good solution to the problem.
It seems much more powerful and simpler to maintain.

I would greatly appreciate if you put some efforts into researching / developing this.
Hopefully we can have this in future.

Thank you for putting thought into not over-complicating the feature!

**Comment by denisSal** [comment]
Yeah, be my guest. We'll continue the discussion about it when I create this feature branch.

Denis
