### ISSUE TITLE
Open vSwitch question

### ISSUE THREAD

**Issue by blinklet** [imunes/imunes#43]
Question: is the LAN switch node implemented by an instance of Open vSwitch?
If so, do you have plans to expose more Open vSwitch functionality to the IMUNES user?
Would you consider, at some point in the future, enabling the OpenFlow or OVSDB functionality and enable connection between Open vSwitch nodes and SDN controllers? This would allow IMUNES to emulate both traditional routing/switching scenarios and software-defined-networking scenarios.
Thanks,
Brian

**Comment by gcetusic** [comment]
Hi @blinklet 

I'm the main developer of the Linux port so here is a long answer to your question. Yes, the LAN switch node is actually an OpenvSwitch instance started by the Openvswitch daemon and we've quietly introduced it in Linux because Linux lacks Netgraph support (switch emulation). While this, along with Docker, certainly makes IMUNES potentially much more powerful than its FreeBSD implementation, we're currently focused on completely syncing and polishing the functionalities of IMUNES on FreeBSD and Linux. IMUNES doesn't really have that much support for switch manipulation because the IMUNES switch is a netgraph object and harder to develop than OpenvSwitch. At some point we'll turn our attention to making IMUNES fully multihost and that's where Docker and OpenvSwitch will come into play. This will probably again mean a lot of retumbling since FreeBSD recently got Docker support with the ZFS storage driver meaning efficient image creation but slow storage that makes it interesting in the future but not worth switching to just yet. In any case, we *would* like to utilize more of OpenvSwitch and Docker's power but it's currently not our top priority. Personally, for the desktop user I'd switch the whole thing to Docker and OpenvSwitch but it would at this point be much slower and it's in production on several commercial servers so it's not really an option. That being said, we fully encourage users to manually connect IMUNES OpenvSwitch instances to external nodes and let us know how it worked.

**Comment by blinklet** [comment]
Thanks! I wasn't thinking about multi-host setup because i am interested in what can be accomplished on a single desktop system. I've used Mininet to emulate SDN networks and I can run multiple instances of OpenFlow-enabled OpenvSwitch all connected to a process running an SDN controller to create an SDN simulation. 
Once you've completed your current development plan, please consider also enabling SDN network emulation as a native feature in a desktop version of IMUNES. I think this would differentiate IMUNES from other open-source network simulators and enable students to run scenarios where traditional routing protocols interact with SDN.
Thanks for your answer.
