### ISSUE TITLE
Custom routing protocol

### ISSUE THREAD

**Issue by jtremback** [imunes/imunes#46]
I'm hoping to find a good testbed for routing protocol development. Does imunes allow one to run arbitrary software on a node that can modify the routing tables?

**Comment by gcetusic** [comment]
Basically, IMUNES uses a custom made Docker image for PC, Host and Router nodes that run a Debian instance with several networking packages and services added (like tcpdump, sshd etc.) The image is them pulled on your local computer from Hub: https://hub.docker.com/r/imunes/vroot/
Depending on the node type, IMUNES starts the services previously packaged inside the Docker image. E.g. Router node runs Quagga as the routing daemon. Here are your options (requires a little bit of Docker knowledge):

1. Connect the node to the outside world and install your custom software using the rj45 node
- this won't get saved on experiment restart

2. Use Docker to create a custom image and use it instead of the old one. This can be done in several ways:

a) once the experiment is started, Docker containers started by IMUNES are available on the system and you can enter them directly, modify and then use the commit command to create a new image:
https://docs.docker.com/reference/commandline/commit/
- this isn't that clean because it also commits logs and any files you might not want to be around in the image but it's the fastest

b) use our Docker image as a template for your own custom image. We made a repo on Github from which we build the image and publish it on Docker hub: https://github.com/imunes/vroot-linux
- it should be pretty straightforward to clone it, modify it, build the image and change the Docker image IMUNES should use: https://github.com/imunes/imunes/blob/master/runtime/linux.tcl#L1
- my recommendation is that you use our image as the template instead of rolling out your own because IMUNES expects some packages to be installed but if you're feeling adventurous you can create your own from scratch
- in the future we might make the choice of Docker image configurable

Does this answer your question?

**Comment by oikuda** [comment]
I've fixed a bug related to this issue, which makes the procedure described by gcetusic achievable. I will also add a different solution, which is platform indepedent, to this problem later today.
Are you running IMUNES on Linux or FreeBSD?

**Comment by azawlocki** [comment]
Hi, I'm also interested in running custom docker images on nodes. Method 2b) works for me, at least in simple scenarios, but I wonder if this different solution @oikuda mentioned is available?

**Comment by gcetusic** [comment]
On Linux you always have to tinker with Docker while on FreeBSD you have to modify images directly in a folder on your system so I don't think a "platform independent" solution is unlikely to happen anytime soon, other than maybe modifying the setting for the node image in a generic settings file.

**Comment by oikuda** [comment]
Hi,

While the experiment is running you can use the [hcp](https://github.com/imunes/imunes/wiki/Making-scripts-for-IMUNES#hcp) script to copy executable files to running nodes.
After the executable is copied, you can use the [himage](https://github.com/imunes/imunes/wiki/Making-scripts-for-IMUNES#himage) script to start the executable on running nodes.

**NOTE**:The executable must be statically linked or have all needed libraries in the virtual node file system for this to work properly.

Here is a short example for running  the [python_ping project](https://github.com/pferate/python_ping.git) on the topology [p-p.imn](https://github.com/imunes/imunes-examples/blob/master/benchmark/p-p.imn) from the [imunes-examples](https://github.com/imunes/imunes-examples/) repository:
- Clone the imunes-examples repo and start the experiment located in bechmark/p-p.imn. After that clone the python_ping repo, copy the entire folder to the node pc1 and start the ping command:
```console
cd /tmp
git clone https://github.com/pferate/python_ping.git
sudo hcp python_ping pc1:
sudo himage pc1 /python_ping/ping.py 10.0.0.20
```

Alternatively, you can also copy the source files to the running virtual nodes and compile the executable on the nodes. In order for that to work you need to add the build-essentials package and needed libraries to the vroot-linux Docker image.

**Comment by azawlocki** [comment]
Thanks!

**Comment by jtremback** [comment]
I've found that mininet (http://mininet.org/) is possibly a good solution for this, depending on use-case. It's a little more bare bones than Imunes.

**Comment by oikuda** [comment]
IMUNES is also bare bones.
After you create a .imn file for the testbed you can start the experiment from a headless environment (without GUI). After that you run the needed tests and then you terminate the experiment. Basic example with the [p-p.imn](https://github.com/imunes/imunes-examples/blob/master/benchmark/p-p.imn):

- Start the experiment:
```console
$ sudo imunes -b p-p.imn
Creating nodes...
100.0%                                          
Creating links...
100.0%                                          
Configuring nodes...
100.0%                                          
Starting services...
Network topology instantiated in 0.698 seconds (2 nodes and 1 links).
Experiment ID = i1ff0
```
- Check whether the experiment is running with `himage -l`:
```console
$ sudo himage -l
i1ff0 (pc1 pc2)
```
- Run the ping command on pc1 towards pc2:
```console
$ sudo himage pc1 ping -c 3 10.0.0.21
PING 10.0.0.21 (10.0.0.21) 56(84) bytes of data.
64 bytes from 10.0.0.21: icmp_seq=1 ttl=64 time=0.074 ms
64 bytes from 10.0.0.21: icmp_seq=2 ttl=64 time=0.063 ms
64 bytes from 10.0.0.21: icmp_seq=3 ttl=64 time=0.059 ms
--- 10.0.0.21 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.059/0.065/0.074/0.009 ms
```
- Check whether pc2 has an arp record for pc1 (10.0.0.20):
```console
$ sudo himage pc2 arp -an
? (10.0.0.20) at 42:00:aa:00:00:00 [ether] on eth0
```
- Terminate the experiment:
```console
$ sudo imunes -b -e i1ff0
Using experiment ID 'i1ff0'.
Stopping ngraphs and vimages...
100.0%                                          
Destroying links...
100.0%                                          
Shutting down vimages...
100.0%                                          
Cleanup completed in 0.539 seconds.
```

#### This can also be scripted to output simple data, e.g.:
```bash
#!/bin/bash

sudo imunes -b p-p.imn

sudo himage pc1 ping -qc 3 10.0.0.21
if [ $? -ne 0 ]; then
    echo "ping failed"
    exit
fi;

sudo himage pc2 arp -an

# terminate all running experiments
sudo cleanupAll
```
A sample output looks like this:
```console
$ bash test.sh 
...
Network topology instantiated in 0.938 seconds (2 nodes and 1 links).
Experiment ID = i107a
PING 10.0.0.21 (10.0.0.21) 56(84) bytes of data.
--- 10.0.0.21 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.024/0.033/0.045/0.008 ms
? (10.0.0.20) at 42:00:aa:00:00:00 [ether] on eth0
Cleaning experiment with eid i107a.
...
Cleanup completed in 0.547 seconds.
```
