### ISSUE TITLE
Enabling network access from the host to the nodes (in Linux)

### ISSUE THREAD

**Issue by azawlocki** [imunes/imunes#48]
I'm trying to enable network connection between the host and the nodes in my emulated network. I guess a RJ45 node should be used for this but it seems that it's not working yet in Linux.

I've started tinkering a bit with imunes sources. I've removed `net="none"` from the `docker run` command here: https://github.com/imunes/imunes/blob/master/runtime/linux.tcl#L337 to enable default docker bridge network in each node. Then I've created a simple configuration with two PC nodes connected through a switch and edited the corresponding `.imn` file by hand to rename the interface created by imunes at each PC to `eth1` (since `eth0` is already created by docker for the bridge network). 

Now it seems everything works fine, at least for this simple scenario. Do you think I will run into trouble using this approach with more complex networks? Or maybe there is a simpler way to achieve this, without modifying imunes sources?

**Comment by denisSal** [comment]
Hello.
Thank you very much for analyzing the problem and giving us valuable input.

The RJ45 node is meant to connect an entire IMUNES experiment to an external network by capturing the inerface into the experiment (this means that the interface would be used only by IMUNES and would not be available on the host OS after starting the experiment). This enables seamless interaction of IMUNES experiments with an external network environment. This behaviour was inherited from FreeBSD version which preceded the Linux version of IMUNES. If you have an additional RJ45 interface on your physical machine, it can be used for connecting to the topology from the outside.

However, the feature you are interested in was previously discussed by the IMUNES team and we agree that such a feature should be implemented. The implementation of this feature should also include GUI changes in the form of introducing a new type of node. We will start working on that feature next week. This new type of node would enable accessing an entire network segment from the local machine instead of giving individual access to every container (virtual node) by default.

We haven't tested your approach, so we cannot be certain about its implications. Your approach makes every node in the experiment accessible to the local machine and also to the outside environment (since every machine can then access the Internet).

**Comment by azawlocki** [comment]
Thanks for the clarifications! I will be checking for the updates in the
IMUNES repo then and will use my workaround until the new feature is ready.

**Comment by oikuda** [comment]
There is an option on every docker L3 node in the GUI (pc, router, host) which enables adding an external interface to the docker node. The interface is named ext0 and its address can be printed out in the following manner:
```console
# himage node_name ip a show dev ext0
```
Through this address the docker node can access the external network and can be accessed from the machine running the experiment.
@azawlocki This is a workaround similar to the one you suggested, but it can be specified on per node basis. Introducing additional external interface node type is in the works.

**Comment by azawlocki** [comment]
Works fine for me and is much cleaner than the workaround I used. Thanks.

**Comment by denisSal** [comment]
Hi!

Just a heads up for anyone reading this: we created a new node in a875f3ea7be92b8b15c987c11d0103eb0e7c06f3 which is used to connect to the running topology.
This node creates a new interface on your local machine which is directly connected to one node in your topology (i.e. a switch). This interface gets IPv4 and IPv6 addresses just like any other L3 node and you can access it or modify it just like any other interface on your system.
Note that the default route for your machine is not changed, so you will have to manually add all the neccessary routes from your topology.
