### ISSUE TITLE
Ability to run different docker images/containers for PC and Host nodes

### ISSUE THREAD

**Issue by maxpfingsthorn** [imunes/imunes#52]
It would be great to include an option in the configuration for PC and Host nodes which allows to pick a docker image to run for a specific node. Or, as an alternative, choose a docker container by name/id that should already be instantiated (appears in docker ps -a). The second option would allow using complex docker parameters (mounting volumes and devices, setting env variables, running privileged, etc), which I guess would be slightly more involved to implement. Though I guess a string (text field for the GUI) for extra docker args would suffice. Maybe this can be complementary to the custom config feature.

This is a kind of extension of #51, where the answer was to switch the image started for any and all nodes in the network. Here, though, I am especially interested in starting different images for different nodes.

It would be useful to document requirements for the docker image in order to use it with IMUNES in any case.

Thanks for the great work so far!

**Comment by denisSal** [comment]
Hi!

We already considered doing something like this, but we were still in early Linux development so that idea was abandoned. However, Linux port is now quite stable, so we should start thinking about implementing this functionality (or something similar).

It certainly would be useful to document requirements for docker images, so this will be our first step.

Thank you for your suggestion and expect further updates on this issue soon.

**Comment by maxpfingsthorn** [comment]
Thanks for the feedback! Are you actively working on this? If not, I could look into the issue in a week or so (I have other deadlines before that). In any case, I'd be happy to help testing.

**Comment by denisSal** [comment]
There are currently some other priorities for us, so we would be happy if you look into this whenever you can. :)

**Comment by denisSal** [comment]
Implemented this in db36ce475803ef025fb6b7078a4577dbb19e3470 .
