### ISSUE TITLE
Virtual Linux Machines

### ISSUE THREAD

**Issue by tahiry** [imunes/imunes#73]
Hi all,

- Is it possible to run debian as a virtual machine inside imunes  experiements instead of freebsd ? 
- Is it possible to customize the freebsd virtual machine inside imunes experiments (packages, configuration, etc...) ? 

Regards,
/t

**Comment by denisSal** [comment]
Hi!

1. When IMUNES is installed on FreeBSD, it's not possible to run Linux VMs because we use FreeBSD jails to run nodes. Installing IMUNES on Linux runs Debian based Docker containers as nodes, but some functionality from FreeBSD is not supported on Linux.

2. Yes, it is possible to change it, either in runtime (changes are lost on experimet termination), or by changing the virtual root located in /var/imunes/vroot (this keeps changes). The installed tools `pkg_imunes` (on FreeBSD) or `apt-get_imunes` (on Linux) could also help. These tools are used to install packages in the virtual root. You use them by running: `pkg_imunes install package-name` or `apt-get_imunes install package-name`.

If you have any more questions about this, feel free to ask here.

Kind regards,
Denis

**Comment by 7ahiry** [comment]
Hi,

Following remark number 2. When I save an experiement is it possible to also save the state of each machine, not only topologies ? Let me make myself clear if needed. 

I execute an experiment (Menu/Experiment/Execute), I've made some changes say in pc1: downloaded some specific files, run services, etc... Can the state of pc1 be saved when experiement is saved ? 

Regards,

/tahiry

**Comment by denisSal** [comment]
**Linux**

There is a commit 013c16fcbadb00a3fcca63e04589b880053d0c0c in the `docker_another` branch which adds a GUI text box for defining a different docker image for IMUNES to load. If you are familiar with docker, create your custom docker image with all the necessary files/services and add a node in IMUNES with the name of your image. This is not quite tested yet, so you should be careful.

**Linux and FreeBSD**

Nodes have options to start some of the services automatically (ssh, ftp, telnet, ipsec), but I guess you need something else. This could be done with `Custom startup config`:
- Enable it in the node configuration window.
- Click `Editor`.
- Type a name (e.g. myconf) and click `Create`.
- Click `Fill defaults` to fill the text box with the default values.
This is just a list of commands that are run on the startup of the node, one by one. You can run anything you would otherwise run after starting the experiment.

Another solution is to write scripts (see [himage and hcp](https://github.com/imunes/imunes/wiki/Making-scripts-for-IMUNES)) from outside of your experiment and run them every time your experiment is executed. 

Files in /var/imunes/{eid} are nodes' runtime filesystems, you cannot use them in this manner.

Regards,
Denis
