### ISSUE TITLE
Internet Access for a virtual machine

### ISSUE THREAD

**Issue by 7ahiry** [imunes/imunes#74]
Hi,

I would like a virtual machine inside imune to access the internet. My intuition says that it is done through the "external connection" entity. But I do not know how to do it. Is there any documentation regarding "external connection" ?  

Regards,

/tahiry

**Comment by denisSal** [comment]
`External connection` is used for connecting your host PC to your IMUNES topology.

You need `External interface`: this node 'steals' one of your host interfaces and 'gives' it to IMUNES, so it behaves like an exit point to internet (on FreeBSD, if you don't create a bridge, that interface becomes invisible to your host).
Example: 3 PC nodes connected to a switch, connected to an `External interface`.

![image](https://user-images.githubusercontent.com/10561979/47008680-06133d80-d13b-11e8-9ace-26be0bac9419.png)

`External interface` node is configured to work with 'br0' physical interface. I created a bridge 'br0' on my host machine and connected it to my real external interface which I use to connect to the internet (I created a bridge with a short name because our naming convention prevents us from using long external interface names on Linux; this is a known bug).

To reach the internet, assign a static IP address, route (and DNS nameserver) or just run dhclient on the node.

In the example above, every PC node can reach the internet.

**Comment by jleman** [comment]
So if I understand correctly, you setup two virtual networks in FreeBSD and bridged between them?  If so, what VM software are you using?  I am trying to do the same thing using Hyper-V, but am not able to get FreeBSD to setup more than one virtual network.

**Comment by denisSal** [comment]
If I understood correctly, your Windows PC is connected to the `hn0` interface, which is brigded to `hn1` interface, which is connected to `CC_Router` node... Is that right?

Does your Windows PC have an IP address and a default router? It needs to have an IP address from the 10.0.7.0/24 subnet and it needs to have `CC_Router` IP address (10.0.7.1) as a default router.

Can you use `hn0` instead of `hn1` in your topology to connect directly to your PC without bridging? I'm not really sure I understand what exactly are those two interfaces connected to?

Regards,
Denis

**Comment by jleman** [comment]
Thanks for the reply.  I am very new to networking so apologies for my inability to describe properly.  I have FreeBSD and IMUNES running inside a Hyper-V virtual machine.  Using Hyper-V I have associated two virtual network adapters with the FreeBSD virtual machine.  Each is also associated with a virtual switch. Within Windows network settings I have assigned a static IP to the virtual networks. When I boot up the VM, FreeBSD recognizes these virtual adapters as hn0 and hn1.  Then using ifconfig from within FreeBSD I assign static IPs to hn0 and hn1.  At this point (IMUNES not yet running), I can ping the FreeBSD IP address for hn0 and hn1 from a windows terminal and vice versa.  

Example Windows settings:
VirtualNetwork1:  10.0.10,11  netmask 255.255.255.0
VirtualNetwork2:  10.0.11.12  netmask 255.255.255.0

From within FeeBSD:
hn0 (corresponds to VirtualNetwork1):  use ifconfig to set IP of 10.0.10.10
hn1 (corresponds to VirtualNetwork2):  use ifconfig to set IP of 10.0.11.11

If I start the IMUNES exeriment with hn0 or hn1 as the 'external connection 'then I can no longer ping the corresponding IP address from outside the VM.  If I understand your comments above, this is expected behavior - IMUNES steals the selected node.  

I then created a bridge between hn0 and hn1.  My understanding is that if I select hn1 as the IMUNES 'external connection' it will be come invisible to Windows, but I can still use hn0 as the actual external connection due to the bridge.  I think I must have some concept error here as it does not work.

**Comment by denisSal** [comment]
First of all, I tried to do this on Hyper-V and I have some questions for you...
What type of Hyper-V networks are VirtualNetwork1 and VirtualNetwork2 (External, Internal, or Private)?
Do you need two network interfaces in your FreeBSD machine?
Are you willing to show me your Windows `ipconfig \all` output (only vEthernet adapters)?

Your approach here is wrong but I will try to explain it so you can make it work, but first I need to make sure I understand what you really want.

**Comment by jleman** [comment]
Ultimately I am trying to connect a MODBUS TCP client to a MODBUS TCP server via the emulated network in IMUNES.  Both the MODBUS client and server are running in windows so I assumed I would need an external connection for each,  The client will be polling the server for data while we examine the impact of various network link failures in the emulated network.  The figure below illustrates the overall topology.

![image](https://user-images.githubusercontent.com/44458380/55625283-21abe800-575d-11e9-882f-9a839205d68e.png)

I have the Hyper-V VMs set to internal (not sure if this right).  I emailed you the ipconfig information.

**Comment by gornjas** [comment]
jleman: as outlined in your topology figure, both the Modbus server and client are running in the same OS & network address space. The OS (Windows 10) will use internal loopback connection when establishing TCP sessions from the client to the server, and the packets will never cross the host OS / Hyper-V boundary (regardless of the OS running in the VM).  I.e. I don't see how do you intend to instruct the Windows network stack to route the TCP session through the Hyper-V VM. IMO your experiment would have better chances of succeeding if you would run two Windows 10 VM machines, one for the server, and the other for the client, each on a different IP subnet, and then route the traffic through IMUNES.

**Comment by jleman** [comment]
Thank you.  I was worried about that, but was focusing on first trying to figure out proper syntax and setup of a single external interface from FreeBSD/IMUNES.  

Perhaps something like this would work?
![image](https://user-images.githubusercontent.com/44458380/55632350-f7fbbc80-576e-11e9-9742-0fd4200e4270.png)

**Comment by denisSal** [comment]
> Thanks for the reply. I am very new to networking so apologies for my inability to describe properly. I have FreeBSD and IMUNES running inside a Hyper-V virtual machine. Using Hyper-V I have associated two virtual network adapters with the FreeBSD virtual machine. Each is also associated with a virtual switch. Within Windows network settings I have assigned a static IP to the virtual networks. When I boot up the VM, FreeBSD recognizes these virtual adapters as hn0 and hn1. Then using ifconfig from within FreeBSD I assign static IPs to hn0 and hn1. At this point (IMUNES not yet running), I can ping the FreeBSD IP address for hn0 and hn1 from a windows terminal and vice versa.
> 
> Example Windows settings:
> VirtualNetwork1: 10.0.10,11 netmask 255.255.255.0
> VirtualNetwork2: 10.0.11.12 netmask 255.255.255.0
> 
> From within FeeBSD:
> hn0 (corresponds to VirtualNetwork1): use ifconfig to set IP of 10.0.10.10
> hn1 (corresponds to VirtualNetwork2): use ifconfig to set IP of 10.0.11.11
> 
> If I start the IMUNES exeriment with hn0 or hn1 as the 'external connection 'then I can no longer ping the corresponding IP address from outside the VM. If I understand your comments above, this is expected behavior - IMUNES steals the selected node.
> 
> I then created a bridge between hn0 and hn1. My understanding is that if I select hn1 as the IMUNES 'external connection' it will be come invisible to Windows, but I can still use hn0 as the actual external connection due to the bridge. I think I must have some concept error here as it does not work.

You don't have to create a bridge on FreeBSD, but you have to modify the `CC_router`'s interface that is connected to `hn1` to have a MAC address and an IP address of VirtualNetwork1. Then, you should be able to ping the router from your Windows. This configuration works for me.

**Comment by jleman** [comment]
> you have to modify the CC_router's interface that is connected to hn1 to have a MAC address and an IP address of VirtualNetwork1

Is that done within Hyper-V?

**Comment by gornjas** [comment]
jleman: the revised topology with an external PC2 should work IMO. Moreover, PC2 should be replaceable by another Hyper-V VM instance of Windows.

Personally I have no experience with windows containers you mentioned earlier. If they only provide process isolation but with a shared network address space, this wouldn't help much. But if the new Windows versions offer network stack virtualization in combination with process isolation that would be real news...

**Comment by denisSal** [comment]
@jleman 

I played with Hyper-V and Windows for a bit and made it work.

Hyper-V needs to have two 'Internal network' interfaces (just like you do) VirtualNetwork1 and VirtualNetwork2.
I created two Hyper-V VMs: one running IMUNES network topology (FreeBSD 12.0 with IMUNES installed) and one running the 'client' node (FreeBSD with a basic TCP application).

**The IMUNES VM:**
I created two Network adapters (connected to VirtualNetwork1 and VirtualNetwork2) and in `Advanced Features` of both of them clicked on `Enable MAC address spoofing`. This is important.
In FreeBSD, my Hyper-V interfaces match to `hn0` and `hn1` just like yours do. In IMUNES, I created two External interfaces and selected `hn0` and `hn1`. I attached a basic IMUNES topology and I will explain my configuration based on it. Notice that you don't have to assign any IP addresses to `hn0` or `hn1` in FreeBSD.

![image](https://user-images.githubusercontent.com/10561979/55742921-48a23c80-5a31-11e9-8278-f914c767bae5.png)

**The 'client' VM:**
I created one Network adapter (connected to VirtualNetwork1) and clicked on `Enable MAC address spoofing`. This is important.
When the VM started, I assigned the interface (`hn0`) an IP address from the subnet of the `eth1` interface of `router1`, and set its default router as an `router1`'s IP address. For example:
```
# ifconfig hn0 10.0.10.111/24 # 'client' IP address
# route add default 10.0.10.1 # 'client' default router
```
With this, I can ping the `pc1` node from my 'client' VM and vice versa.

To enable the communication between my 'client' VM and some TCP application listening on my Windows host, I needed to do the following...
I set the IP address of the vEthernet (VirtualNetwork2) to 10.0.11.12, its mask to 255.255.255.0 and its default gateway to `router1`'s `eth0` IP address, 10.0.11.1.
Then, I set the IP address of vEthernet (VirtualNetwork1) to 'Obtain automatically' because I don't want this adapter to have an IP address.
Next, because my Windows host now doesn't know about the 10.0.10.0/24 subnet, I needed to add this route to go over the `router1` through VirtualNetwork2:
```
route add 10.0.10.0 mask 255.255.255.0 10.0.11.1
```
With this, I can connect from my 'client' VM to the Windows host (10.0.11.12) and vice versa through IMUNES.

I hope this helps. If you have any more questions, please ask.

Regards,
Denis

**Comment by jleman** [comment]
Thank you for the additional information above.  It was very helpful and I was able to get most everything working.  However, it turns out that the firewall policy from my IT group prevents some actions so I am moving the entire setup to virtual machines.  This my new setup:

![image](https://user-images.githubusercontent.com/44458380/56549163-e704c680-6536-11e9-8a4f-11fc815e7ad0.png)

I implemented your suggestions in the simple IMUNES network above and I am able to ping between the two Windows 10 virtual machines.  My experiment requires passing data over a TCP connection between the two Windows 10 VMs (MODBUS communications).  Are you aware of anything within IMUNES that would impede TCP communications? Even though I can ping between the two VMs I am not able to establish a telnet session between them.

**Comment by denisSal** [comment]
This should definitely work (IMUNES would not meddle with any connection). You can try to capture traffic on `router1` node. Run this on the FreeBSD console and try to connect with telnet:
```
# himage router1
# tcpdump -ni eth0
or
# tcpdump -ni eth1
```

If you assigned IP addresses to FreeBSD vswitches, try removing them (such as 10.0.10.9/24 or 10.0.11.10/24).

**Comment by jleman** [comment]
Yes, I was assigning IP address to FreeBSD vswitches.  I deleted those per your suggestion and tried again.  Still no connection.  From telnet:

![image](https://user-images.githubusercontent.com/44458380/56569703-5b0e9100-656e-11e9-8a39-27052f66c51c.png)

the himage command didn ot work, but I was able to run the TCDUMP followed by the telnet attempt:

![image](https://user-images.githubusercontent.com/44458380/56569774-82655e00-656e-11e9-8b0a-3fb426c11972.png)

eth0:
![image](https://user-images.githubusercontent.com/44458380/56569792-8abd9900-656e-11e9-8723-67ec7bd532a4.png)

eth1:
![image](https://user-images.githubusercontent.com/44458380/56569813-914c1080-656e-11e9-8c2b-a609725e5f35.png)

If I understand these correctly, the request is being passed through, but is not being accepted.  Must be some kind of setting int he Windows 10 VMs or Hyper-V.

**Comment by denisSal** [comment]
> Yes, I was assigning IP address to FreeBSD vswitches. I deleted those per your suggestion and tried again. Still no connection. From telnet:
> 
> ![image](https://user-images.githubusercontent.com/44458380/56569703-5b0e9100-656e-11e9-8a39-27052f66c51c.png)
> 
> the himage command didn ot work, but I was able to run the TCDUMP followed by the telnet attempt:
> 
> ![image](https://user-images.githubusercontent.com/44458380/56569774-82655e00-656e-11e9-8b0a-3fb426c11972.png)
> 
> eth0:
> ![image](https://user-images.githubusercontent.com/44458380/56569792-8abd9900-656e-11e9-8723-67ec7bd532a4.png)
> 
> eth1:
> ![image](https://user-images.githubusercontent.com/44458380/56569813-914c1080-656e-11e9-8c2b-a609725e5f35.png)
> 
> If I understand these correctly, the request is being passed through, but is not being accepted. Must be some kind of setting int he Windows 10 VMs or Hyper-V.

Yeah, it seems to be working... 

I managed to connect via TCP with your setup by assigning IP addresses 'from inside' the virtual machines, without assigning any IP addresses to any vswitch from the host Windows VM, so I don't know what is the problem.

**Comment by jleman** [comment]
What virtual machine platform were you using (Virtual Box, Vmware, Hyper-V, other?). Could you post a screen shot of the virtual switch settings?

**Comment by denisSal** [comment]
Hyper-V.

I have two Private network Virtual switches. Only Microsoft NDIS Capture is checked (by default) in Extensions.

Each non-IMUNES VMs are connected to a different Virtual switch and created with default settings except for "Enable MAC address spoofing" which is checked for me on both VMs:

**VirtualNetwork1/VirtualNetwork2**
Enable virtual LAN identification - unchecked
Enable bandwidth management - unchecked

**Hardware acceleration**
Enable virtual machine queue - checked
Enable IPsec task offloading - checked

**Advanced features**
Enable MAC address spoofing - checked
Enable DHCP guard - unchecked
Enable router advertisement guard - unchecked
Protected network - checked
Mirroring mode - None
NIC Teaming - unchecked

**Comment by jleman** [comment]
Thanks.  What VMs did you use (Windows, Linux, other?)

**Comment by denisSal** [comment]
Sorry, forgot to mention... Windows Host and 3 FreeBSD-12 VMs.
