### ISSUE TITLE
Firewall in FreeBSD

### ISSUE THREAD

**Issue by idahogray** [imunes/imunes#84]
I have been searching around and it looks like it is possible to run pf inside of a FreeBSD 12 VMNET jail. I tried enabling pf in /etc/rc.conf but I still get an error in a imunes host when I try to run `pfctl -e`.

```
pfctl: /dev/pf: No such file or directory
```

Searching around on that error makes it look like I need to enable the dev directory in the jails. I am hoping someone can help me figure out how to do that or if there is another way to enable a firewall in the hosts/PCs in imunes.

Thanks in advance.

**Comment by denisSal** [comment]
Hi!

Two things are needed to run pf:
1. enable `pf` kernel module,
2. add /dev/pf* to devfs ruleset 46837 (IMUNES' ruleset).

1. is easy: you can just `kldload pf` or `pf_load="YES"` in `/boot/loader.conf` (to enable `pf` at boot).
2. is also easy, you just run: 
```
# devfs ruleset 46837
# devfs rule add path pf* unhide
# devfs ruleset 0
```

If you want to add this functionality to IMUNES, you could add the line `devfs rule add path pf* unhide` to a list of other devfs rules in a function `prepareDevfs` in a file `runtime/freebsd.tcl` and install IMUNES (reboot needed).

P.S. you can also use the `ipfw` firewall. In that case, the only thing you need to do is enable the kernel module `ipfw` instead of `pf` (no devfs ruleset change is necessary). Also, I would recommend adding `sysctl net.inet.ip.fw.default_to_accept=1` to your `/boot/loader.conf` so you don't have to explicitly accept on every node (reboot needed).

Regards,
Denis

**Comment by rajhlinux** [comment]
This is what I get:

```
$ ssh -p 2222 user@192.168.0.104

client_loop: send disconnect: Broken pipe

ssh: connect to host 192.168.0.104 port 2222: No route to host
```
Why is it doing this?

Thanks.
